# E2E/dbt/Dockerfile.pyDBT
FROM python:3.12-slim

WORKDIR /usr/app/dbt

COPY requirements.txt .

# Aumentamos el timeout a 1000 segundos para evitar errores de conexión/descarga.
RUN pip install --default-timeout=1000 --no-cache-dir -r requirements.txt dbt-core dbt-postgres

COPY . .

# Usamos la sintaxis exec (JSON array) para el CMD, que es la forma recomendada en Docker.
CMD ["dbt", "build", "--target", "dev"]