nyc_911_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db      # <--- CAMBIA 'localhost' POR 'database'
      user: postgres    # <--- OJO: Asegúrate de que esto coincide con el docker-compose
      password: postgres # <--- OJO: Asegúrate de que esto coincide con el docker-compose
      port: 5432
      dbname: new_york
      schema: public
      threads: 4