from python:3.11-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    git

RUN useradd -m dashboarduser
WORKDIR /app/dashboard
COPY dashboard.py .
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN chown -R dashboarduser:dashboarduser /app/dashboard
USER dashboarduser